### ISSUE TITLE
Getting ShiningPanda Python location does not work on Windows

### ISSUE THREAD

**Issue by torbjoernk** [jenkinsci/pyenv-pipeline-plugin#12]
As reported on Nov 29th, 2017 in the official Jenkins issue tracker as [JENKINS-48276](https://issues.jenkins-ci.org/browse/JENKINS-48276):

> The plugin doesn't work correctly using the ShiningPanda tool location:
> ```
> Matched ShiningPanda tool name: Windows-Python-Default
> $ C:\Python27\python -m virtualenv --python=C:\Python27\python C:\jenkins\workspace\Python\pymxf\.pyenv-Windows-Python-Default
> Error while creating virtualenv: The path C:\Python27\python (from --python=C:\Python27\python) does not exist
> ```
> The --python argument expects the full filename (C:\Python27\python.exe in this case). Specifying the full path in the tool configuration still causes this plugin to try to append "python" to the string.

Are there any plans on when this issue is getting fixed?

**Comment by cstarner** [comment]
I apologize for the delay. I will be releasing a fix either later today or tomorrow

**Comment by torbjoernk** [comment]
@cstarner Thank you very much and no worries about the delay. After all, this is open source :smiley: I'll update and test the plugin on Monday.

/Edit/
Works flawlessly. I'll buy you a beer (or another cold refreshing beverage) once we meet somewhere.
