### ISSUE TITLE
Spaces in job name cause Shebang PATH problem

### ISSUE THREAD

**Issue by robjsch** [jenkinsci/pyenv-pipeline-plugin#14]
If you have spaces in a Jenkins job name the Shebang written in the virtualenv pip will not be found, causing the system to fall back to the next python binary in the path (and outside of the virtualenv).

**Comment by cstarner** [comment]
This is a long established issue with virtualenv itself: pypa/virtualenv#53. 

Unfortunately, there isn't much I can do, short of you providing more information that would indicate that this bug arises specifically from the use of this plugin
