### ISSUE TITLE
Incorrect drive letter substitution on Windows

### ISSUE THREAD

**Issue by climblinne** [jenkinsci/pyenv-pipeline-plugin#17]
When using another drive on Windows D: or even c: the plugin is not working correct.

Please replace in WithPythonEnvStep.java (line 73)

```
 String postfix = pythonInstallation.replaceAll("/", "-")
                .replaceFirst("C:\\\\", "")
                .replaceAll("\\\\", "-");
```

with 

```
 String postfix = pythonInstallation.replaceAll("/", "-")
                .replaceFirst("[a-zA-Z]:\\\\", "")
                .replaceAll("\\\\", "-");
```

**Comment by cstarner** [comment]
Thank you for bringing this to my attention. I've fixed it and am closing this issue.

Always feel free to submit a pull request, especially for small stuff like this.
