### ISSUE TITLE
"No such file or directory" for any pysh when Jenkins project name contain spaces

### ISSUE THREAD

**Issue by tal5ab** [jenkinsci/pyenv-pipeline-plugin#3]
i renamed my project , and my pipeline stopped working
I was getting : 

> [aa aa] Running shell script
> + . '/var/jenkins/workspace/aa aa/.pyenv-usr-local-bin-python3.6/bin/activate;' ls -la
> /var/jenkins/workspace/aa aa@tmp/durable-e7579f4b/script.sh: line 2: /var/jenkins/workspace/aa aa/.pyenv-usr-local-bin-python3.6/bin/activate;: No such file or directory
> 

Removing the spaces in the project name fixed the issue

```
withPythonEnv('/usr/local/bin/python3.6'){
                //Build
                pysh 'ls -la'
            }
```

**Comment by cstarner** [comment]
The fix has been incorporated in v1.0.3
