### ISSUE TITLE
.pyenv-python.exe/bin/activate: No such file or directory on Windows

### ISSUE THREAD

**Issue by jitbasemartin** [jenkinsci/pyenv-pipeline-plugin#5]
Hello,

I don't know if I use the plugin correctly but I got this error on Windows:
`.pyenv-python.exe/bin/activate: No such file or directory`

My pipeline code is:
```
    node("WINDOWS") {
        stage("Install") {
            withPythonEnv("python.exe") {
                pybat "python setup.py install"
            }   
        }
    }
```

I use:
- Jenkins: `2.73.2`
- Pyenv Pipeline Plugin: `1.0.3`
- Windows 7

If I browse my workspace the activate script is in `.pyenv-python.exe\Script\activate` maybe it's the problem ?

Thanks

**Comment by cstarner** [comment]
That error is caused by using a `pysh` step on a Windows machine. Double-check and make sure that all of the commands that occur within the `withPythonEnv` block are `pybat`

**Comment by jitbasemartin** [comment]
Thanks I forgot to change all my `pysh` by `pybat`
